apiVersion: v1
kind: Service
metadata:
  name: medicare-frontend
  namespace: medicare-dev
  labels:
    app: medicare-frontend
    environment: dev
    project: medicare

spec:
  type: ClusterIP

  selector:
    app: medicare-frontend

  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
