apiVersion: v1
kind: Secret
metadata:
  name: medicare-backend-secret
  namespace: medicare-dev
  labels:
    app: medicare-backend
    environment: dev
    project: medicare
type: Opaque
stringData:
  DB_USERNAME: "medicareuser"
  DB_PASSWORD: "CHANGE_ME"
