apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: medicare-image-updater
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: medicare-app
      useAnnotations: false

      images:
        - alias: backend
          imageName: anitaraut/medicare-backend:v3
          commonUpdateSettings:
            updateStrategy: semver

        - alias: frontend
          imageName: anitaraut/medicare-frontend:v3
          commonUpdateSettings:
            updateStrategy: semver
