spring.application.name=medicare-backend
server.port=8082


# spring.datasource.url=jdbc:mysql://localhost:3306/Medicare
# spring.datasource.username=root
# spring.datasource.password=root123

# DB config

# Database = Medicare
# Username = medicareuser
# Password = root123
# Port     = 3306

# MySQL run

# docker run -d \
#  --name medicare-mysql \
#  -e MYSQL_ROOT_PASSWORD=root123 \
#  -e MYSQL_DATABASE=Medicare \
#  -p 3306:3306 \
#  mysql:8.0

# or 

# database part

# docker run -d \
#  --name medicare-mysql \
#  --network medicare-network
#  -e MYSQL_ROOT_PASSWORD=root123 \
#  -e MYSQL_DATABASE=Medicare \
#  -e MYSQL_USER=medicareuser \
#  -e MYSQL_PASSWORD=medicare123 \
#  -p 3306:3306 \
#  mysql:8.0

# with URL
# this for bcakend part

# docker run -d \
# --name medicare-backend \
#  --network medicare-network \
# -p 8082:8082 \
# -e DB_URL="jdbc:mysql://medicare-mysql:3306/Medicare" \
# -e DB_USERNAME="medicareuser" \
# -e DB_PASSWORD="medicare123" \
#  medicare-backend:v1.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
